
language: python
python:
    - "3.5"
env:
    - IIIFCOLLBROWSE_DEFAULT_COLL=https://iiif-collection.lib.uchicago.edu/top.json
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb time to start
    - pip install python-coveralls
addons:
    - firefox 
before_install:
    # how-to get geckodriver added see https://github.com/travis-ci/travis-ci/issues/7068
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.0/geckodriver-v0.20.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.20.0-linux32.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
install: 
    - pip install -r requirements.txt
    - "pip install -r requirements_dev.txt"
    - "python setup.py test"
script: 
    - coverage run --source iiifcollectionbrowse -m py.test 
    - flake8 --exit-zero
after_success:
    - coverage report
    - coveralls

